[package]
name = "Poly-STC-Assets"
version = "2.0.1"

[addresses]
StarcoinFramework = "0x1"
PolyBridge = "0xe52552637c5897a2d499fbf08216f73e"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "7805a6743de2e476c4c912b7f87d22e1b8dcc8ee" }